### ISSUE TITLE
~catclone and other category commands cleanup

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#12]
~~more robust “find category” function~~

**Comment by kevslinger** [comment]
Currently, we only are able to find categories if the capitalization matches exactly. Which is a problem because discord's client auto-caps locks category names, so it is often unclear what the real category name is. Expecting users to auto-caps lock their category names is not reasonable. We should probably find a way to do case-insensitive category name searching.

**Comment by TheOriginalSoni** [comment]
> restrict the search to only categories

To be done in both ~clonecategory and ~movecategory, maybe more

**Comment by TheOriginalSoni** [comment]
move category find to util

take category name as an arg on cat stats as well

**Comment by TheOriginalSoni** [comment]
~clonecat "Cat A" "Cat A" @role1 @role2

Current Behavior - Extremely odd, maybe it removes all possible perms? Idk what's going on.

Intended behaviour - ??? 

Possible future intended behaviour - Maybe just add Role2 with same perms as role1, and keep everything else as is.

**Comment by TheOriginalSoni** [comment]
~pinme if both categories exist, clonecat just syncs the permissions, but no error code/success code generated.

**Comment by TheOriginalSoni** [comment]
Reopening, minor bugs still to be squashed

> take category name as an arg on cat stats as well

Also on synccat

**Comment by TheOriginalSoni** [comment]
> > take category name as an arg on cat stats as well
> Also on synccat

Split into #80

**Comment by TheOriginalSoni** [comment]
> ~clonecat "Cat A" "Cat A" @role1 @Role2
> 
> Current Behavior - Extremely odd, maybe it removes all possible perms? Idk what's going on.
> 
> Intended behaviour - ???
> 
> Possible future intended behaviour - Maybe just add Role2 with same perms as role1, and keep everything else as is.

Done in 527ba90

> If both categories exist, clonecat should just syncs the permissions, but no error code/success code generated currently.

Done in earlier commit
