### ISSUE TITLE
New commands : ~sheetlion ~chanlion ~solvedlion ~mtalion etc

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#25]
Chancrab with Overview integration during creation + solve

- List puzzle on Overview
- Link Overview cell (col B) to tab of puzzle
- Link Overview cell (Col D) to Answer cell in puzzle tab

After solving - 
- Record answer in puzzle tab (And overview if step3 during puzzle creation is not done)
- Mark tab as solved (Green/Blue/whatever colour)

After archiving
- Throw tab towards end of tabs in sheet

During Chanlion, set it to replace PUZZLE-TITLE and PUZZLE-LINK in the tab (probably integrate into chancrab?)
happy emoji on solved (maybe integrate back to solved?)

**Comment by kevslinger** [comment]
Can we please choose a more descriptive command name? Is LION an acronym?

**Comment by TheOriginalSoni** [comment]
Probably also clean up crab functions properly. 

Split each sub function into relevant utils, and reduce duplication

Maybe also add more commenting for better clarity

**Comment by petecao** [comment]
Implemented in dfe77b705c362644b197b7eaf7bfbe5c042dfc88
