### ISSUE TITLE
New command : ~todo

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#29]
With issues subset that we have to do.

Maybe custom command instead?

~~Maybe \~todo 29 pulls up https://github.com/kevslinger/bot-be-named/issues/29~~

**Comment by kevslinger** [comment]
Maybe the command can take a specific label and the bot will return links to all issues of that label. e.g. 
`~todo Priority: Low`

**Comment by TheOriginalSoni** [comment]
Random idea. What if custom commands were allowed to have parameters, like $1

So

`~addcustomcommand issues "https://github.com/kevslinger/bot-be-named/issues/$1"` on setup

`~issues 29` returns `https://github.com/kevslinger/bot-be-named/issues/29`

Will this be easy or feasible

**Comment by TheOriginalSoni** [comment]
> ~~Maybe \~todo 29 pulls up https://github.com/kevslinger/bot-be-named/issues/29~~

Done manually (No fancy parameter thing) in 5bb1857

Keeping issue closed for Fancy Parameter thing or for Label/Priority Search

**Comment by TheOriginalSoni** [comment]
Is there a way to edit ~issues to give the overall issue stats if there's no parameters?

Like just as simple as "38 open issues" or whatever

**Comment by TheOriginalSoni** [comment]
> Random idea. What if custom commands were allowed to have parameters, like $1
> 
> So
> 
> `\~addcustomcommand issues "https://github.com/kevslinger/bot-be-named/issues/$1"` on setup
> 
> `\~issues 29` returns `https://github.com/kevslinger/bot-be-named/issues/29`
> 
> Will this be easy or feasible

Split to #71

**Comment by TheOriginalSoni** [comment]
> Is there a way to edit ~issues to give the overall issue stats if there's no parameters?
> 
> Like just as simple as "38 open issues" or whatever

Gives issue link. Not easy to do stats thing yet. Currently putting as wontfix, might revisit later.
