### ISSUE TITLE
~chancrabsorted features

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#30]
Not all of the solvedsorted etc are implemented
~~Sorted is too slow~~
Chancrabsorted etc isnt implemented
Just remove all commands?

**Comment by TheOriginalSoni** [comment]
Maybe just Chan crab could create the new Chan just below the one calling and then remove every other sorted+X combo command

**Comment by TheOriginalSoni** [comment]
Split sorted is too slow to #43

**Comment by kevslinger** [comment]
Removed in 10d3360e1cbf4b9f58b9684914e3e257ff456302
