### ISSUE TITLE
Remove Master Sheet

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#36]
BBN master sheet still gets updated for every tether. 
Is it moved to DB yet? Is master sheet only copy or duplicated on both?
Eventually delete master sheet now we have DB

**Comment by kevslinger** [comment]
oh this is the issue I was looking for. This was addressed in d361f27

**Comment by petecao** [comment]
All that's left is the ~remindme move to DB in #83 and we can delete the master sheet
