### ISSUE TITLE
Formatting and stylesheet thing

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#37]
Move to black? Something else to keep format consistent?

**Comment by kevslinger** [comment]
Black (**recommended**): https://github.com/psf/black
Autopep8: https://pypi.org/project/autopep8/

**Comment by TheOriginalSoni** [comment]
Done in some earlier push

But also, is there a way to do it automatically on every push isntead of being manually triggered?

**Comment by kevslinger** [comment]
Black will automatically run on pull and push request, per 34f06cc
