### ISSUE TITLE
Allow modules to fail gracefully, disable failed modules

### ISSUE THREAD

**Issue by kevslinger** [kevslinger/bot-be-named#44]
Some modules, e.g. [sheets](https://github.com/kevslinger/bot-be-named/blob/main/modules/sheets/cog.py), fail when they are unable to connect to google sheets. Either because sheets is down, or because someone has not set up their `.env` with appropriate variables. When they fail, the entire bot crashes, which shouldn't happen.

We want modules to fail more gracefully, so the rest of the bot can continue working as intended. Once a module fails, we want some `disabled` flag to turn on so no commands from that module are reachable to prevent further issues.

Perhaps we can take it even one more step, and have a table where server admins can toggle modules on/off depending on their needs.

**Comment by TheOriginalSoni** [comment]
> Perhaps we can take it even one more step, and have a table where server admins can toggle modules on/off depending on their needs.

Done via #101
