### ISSUE TITLE
Pruning Database of old/unused information

### ISSUE THREAD

**Issue by kevslinger** [kevslinger/bot-be-named#45]
There are several cases where the database might have useless information. We have a (large, but) limited amount of database space. Some examples:
- Sheet tethers still persist after a channel or category has been deleted
- Custom commands and prefixes still persist after a bot has left the guild

This could be a multi-part fix. There are events such as `on_guild_leave` and `on_guild_channel_delete` (see `discord.py` [docs](https://discordpy.readthedocs.io/en/stable/api.html#discord-api-events)) we can use to remove all information pertaining to those from our DB.

Alternatively (additionally?), we could prune information from the database every... 6 months? Where we check rows' Guild/channel IDs, and if they don't exist anymore or the bot can't access them, remove the row. Something like that.

**Comment by TheOriginalSoni** [comment]
~prunetether exists for former
