### ISSUE TITLE
New command : ~deletecat

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#47]
It's kinda needed badly at this point ;-;

Ideally : Needs an explicit confirmation using a react?

**Comment by kevslinger** [comment]
We should probably discuss this one a little more before going through with it. We've already discussed this at length multiple times

**Comment by TheOriginalSoni** [comment]
Turns out, it was requested, so i guess it's needed

Restriction level : Server owner only

Required : Some way of saying "Yes I confirm I want to delete this category"

Either a role react that server owner clicks to say "Yes I agree"

Or some setup like cipher race (First use ~nukecat then ~confirmnukecat)

**Comment by petecao** [comment]
Implemented in

**Comment by petecao** [comment]
Implemented in 9cf0874b
