### ISSUE TITLE
Command request: ~herokulog similar to ~errorlog

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#54]
~errorlog gives the logs from errors only.

Can we get ~herokulog similar to it, except it gives you the heroku log since restart, not just error logs?

**Comment by kevslinger** [comment]
See https://github.com/kevslinger/bot-be-named/commit/51a25a286c0a5a6a9558e5d1871bff2874a4b38c. Adding this command requires we add my/you heroku API key to `.env`, and I'm not sure if that's worth it.

**Comment by TheOriginalSoni** [comment]
Sideways implemented with 329c071. Instead of herokulog, it's just giving the command usage log via webhook.

Can implement rest of expected utility via webhooks

**Comment by TheOriginalSoni** [comment]
Closing for now. Will reopen if other features to be added
