### ISSUE TITLE
Editccommand can be removed

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#64]
The function is identical from user pov to addccommand and addcimage

Can just overload them all to those two functions, add aliases and handle the use case within that function.

Should be cleaner I think

(See how ~tether behaves if a tether already exists)

**Comment by kevslinger** [comment]
`addcccommand` and `addcimage` will not overwrite previously existing commands. It prevents people from inadvertently wiping out someone else's command. I disagree.

**Comment by TheOriginalSoni** [comment]
We can always edit editccommand functionality to paste the original reply when you finish editing.

That is a useful feature to have anyway, and will also solve this

**Comment by TheOriginalSoni** [comment]
In the same vein, ~createrole is probably best be deprecated in favour of #60 (clonerole) and ~assignrole, which are much more used

**Comment by TheOriginalSoni** [comment]
> In the same vein, ~createrole is probably best be deprecated in favour of #60 (clonerole) and ~assignrole, which are much more used

Done in 1773648

Based on user feedback, going through with this issue

**Comment by TheOriginalSoni** [comment]
> We can always edit editccommand functionality to paste the original reply when you finish editing.
> 
> That is a useful feature to have anyway, and will also solve this

Splitting into #71

**Comment by TheOriginalSoni** [comment]
Moving the entire issue to #71 since it's better suited
