### ISSUE TITLE
~remindme cleanup

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#83]
Remindme cleanup

**Comment by TheOriginalSoni** [comment]
Splitting from #31 

> Needs some tuning, and for BBN we would push a reminder table to the database instead of using a google sheet, but definitely doable. Would want to involve the time parser from [time_utils](https://github.com/kevslinger/bot-be-named/blob/e89bdf506d9e817ecbc24a236825606f33e88a75/modules/time/time_utils.py#L18)

**Comment by TheOriginalSoni** [comment]
Currently accepts negative time as parameter etc. Can be fixxed

`~remindme -2m "Hi"`

**Comment by petecao** [comment]
Fixed negative time issue in 1a27a32eb38673705c11cf224cd7e77a7cccfa48

**Comment by TheOriginalSoni** [comment]
Remindme was removed in [4d69aa0](https://github.com/kevslinger/bot-be-named/commit/4d69aa0a7b56835edaa22052bed3476eeb855469)

The function was potentially the source of the 429 errors of #98 (Every minute check), and otherwise being unused. Can be re-added if necessary
