### ISSUE TITLE
New commmand : ~getsource

### ISSUE THREAD

**Issue by TheOriginalSoni** [kevslinger/bot-be-named#99]
When used as a reply to a message, just copy pastes the entire message in \`\`\`backticks\`\`\`

Very useful to get source formatting for any message

**Comment by kevslinger** [comment]
So this command is only ever useful for mobile, right?

**Comment by TheOriginalSoni** [comment]
Nope. It's much more useful on PC than mobile.

Anytime someone else writes a specifically formatted message (Using \`single-ticks\` and \*\*bolds\*\* and \*italics\* and \<links\> and \@Mentions etc....) it's basically a pain to copy paste it, without re-formatting it yourself (or asking them for the specific formatting they used)

If BBN can do it (instead of me saving a copy of each message with \`\`\`backticks\`\`\` as well, its perfect)

**Comment by TheOriginalSoni** [comment]
Done in 34e53e3
